<?php
session_start();
require 'db.php';

if (!isset($_SESSION['user_id']) || $_SESSION['role'] !== 'student') {
    header("Location: login.php");
    exit;
}

$user_id = $_SESSION['user_id'];
$studentName = $_SESSION['name'] ?? "Student";
$studentEmail = $_SESSION['email'] ?? "N/A";

// Fetch the most recent assessment timestamp for this student
$stmt = $pdo->prepare("
    SELECT MAX(created_at) as latest
    FROM behavior_responses
    WHERE user_id = ?
");
$stmt->execute([$user_id]);
$latestDate = $stmt->fetchColumn();

if (!$latestDate) {
    die("No behavior assessment results found.");
}

// Fetch all categories in the latest assessment
$stmt = $pdo->prepare("
    SELECT DISTINCT bq.category
    FROM behavior_responses br
    JOIN behavior_questions bq ON br.question_id = bq.id
    WHERE br.user_id = ? AND br.created_at = ?
");
$stmt->execute([$user_id, $latestDate]);
$categories = $stmt->fetchAll(PDO::FETCH_COLUMN);

$behaviorResults = [];

foreach ($categories as $category) {
    // Fetch responses per category
    $stmt = $pdo->prepare("
        SELECT br.score, bq.question_text
        FROM behavior_responses br
        JOIN behavior_questions bq ON br.question_id = bq.id
        WHERE br.user_id = ? AND bq.category = ? AND br.created_at = ?
        ORDER BY bq.id
    ");
    $stmt->execute([$user_id, $category, $latestDate]);
    $responses = $stmt->fetchAll(PDO::FETCH_ASSOC);

    $totalScore = array_sum(array_column($responses, 'score'));

    // Fetch behavior suggestion based on total score
    $stmt2 = $pdo->prepare("
        SELECT recommended_careers
        FROM behavior_suggestions
        WHERE category = ?
        AND min_score <= ? AND max_score >= ?
        LIMIT 1
    ");
    $stmt2->execute([$category, $totalScore, $totalScore]);
    $recommendation = $stmt2->fetchColumn() ?? "No recommendation available";

    $behaviorResults[] = [
        'category' => $category,
        'total_score' => $totalScore,
        'responses' => $responses,
        'recommendation' => $recommendation
    ];
}
?>

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Latest Behavior Assessment Report</title>
<style>
body { font-family: "Segoe UI", Arial, sans-serif; margin: 40px; line-height: 1.6; color: #333; }
.header { text-align: center; border-bottom: 2px solid #007BFF; padding-bottom: 15px; margin-bottom: 30px; }
.header img { width: 80px; height: auto; margin-bottom: 10px; }
h1 { margin: 0; color: #007BFF; }
.student-info { margin-bottom: 20px; padding: 15px; background: #f8f9fa; border-radius: 8px; }
.category-card { margin-bottom: 25px; padding: 20px; border-radius: 10px; background: #f9fbff; box-shadow: 0 4px 12px rgba(0,0,0,0.05); }
.category-card h3 { color: #1976d2; margin-top: 0; }
ul { margin: 0; padding-left: 20px; }
.highlight { background: #e9f5ff; padding: 15px; border-radius: 8px; }
.print-btn { display: inline-block; margin-bottom: 20px; padding: 10px 20px; background: #007BFF; color: white; border: none; border-radius: 6px; cursor: pointer; }
.print-btn:hover { background: #0056b3; }
@media print { .print-btn { display: none; } }
</style>
</head>
<body>

<div class="header">
    <img src="logo.JPG" alt="System Logo">
    <h1>Behavior Assessment Report</h1>
    <p><em>Analyzing Your Latest Behavior Assessment</em></p>
</div>

<div class="student-info">
    <p><strong>Name:</strong> <?= htmlspecialchars($studentName) ?></p>
    <p><strong>Email:</strong> <?= htmlspecialchars($studentEmail) ?></p>
    <p><strong>Date of Assessment:</strong> <?= htmlspecialchars($latestDate) ?></p>
</div>

<?php foreach ($behaviorResults as $res): ?>
<div class="category-card">
    <h3>Category: <?= htmlspecialchars($res['category']) ?></h3>
    <p><strong>Total Score:</strong> <?= htmlspecialchars($res['total_score']) ?></p>
    <h4>Your Answers:</h4>
    <ul>
        <?php foreach ($res['responses'] as $r): ?>
            <li>
                <strong><?= htmlspecialchars($r['question_text']) ?></strong> - Score: <?= htmlspecialchars($r['score']) ?>
            </li>
        <?php endforeach; ?>
    </ul>
    <h4>Recommended Behavior Guidance:</h4>
    <div class="highlight">
        <p><?= nl2br(htmlspecialchars($res['recommendation'])) ?></p>
    </div>
</div>
<?php endforeach; ?>

<br><br>
<p><em>Generated by OrientaCore Career & Behavior Guidance System</em></p>
<button class="print-btn" onclick="window.print()">🖨 Print / Save as PDF</button>

</body>
</html>
