<?php
require 'db.php';

if (session_status() === PHP_SESSION_NONE) {
    session_start();
}

// Accept both GET and POST for flexibility
$report_id = $_GET['report_id'] ?? $_POST['report_id'] ?? null;

if (!$report_id) {
    die("No report selected.");
}

// Fetch report details
$stmt = $pdo->prepare("SELECT * FROM counselor_reports WHERE id = ?");
$stmt->execute([$report_id]);
$report = $stmt->fetch(PDO::FETCH_ASSOC);

if (!$report) {
    die("No report found.");
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Counseling Report - <?= htmlspecialchars($report['student_name']); ?></title>
    <style>
        body {
            font-family: "Segoe UI", Arial, sans-serif;
            margin: 40px;
            line-height: 1.6;
            color: #333;
            background: #f8f9fa;
        }
        .header {
            text-align: center;
            border-bottom: 2px solid #007BFF;
            padding-bottom: 15px;
            margin-bottom: 30px;
        }
        .header img {
            width: 70px;
            height: auto;
            margin-bottom: 10px;
        }
        h1 {
            margin: 0;
            color: #007BFF;
        }
        .student-info, .report-details {
            background: #fff;
            border-radius: 8px;
            padding: 20px;
            box-shadow: 0 3px 6px rgba(0,0,0,0.1);
            margin-bottom: 25px;
        }
        .student-info p, .report-details p {
            margin: 6px 0;
        }
        h2 {
            color: #007BFF;
            margin-bottom: 10px;
            border-bottom: 1px solid #ddd;
            padding-bottom: 5px;
        }
        .print-btn {
            display: inline-block;
            margin-top: 15px;
            padding: 8px 15px;
            background: #007BFF;
            color: white;
            border: none;
            border-radius: 6px;
            cursor: pointer;
        }
        .print-btn:hover {
            background: #0056b3;
        }
        .back-link {
            display: inline-block;
            margin-top: 20px;
            text-decoration: none;
            color: #007BFF;
            font-weight: bold;
        }
        .back-link:hover {
            text-decoration: underline;
        }
        @media print {
            .print-btn, .back-link {
                display: none;
            }
        }
    </style>
</head>
<body>

    <div class="header">
        <img src="logo.JPG" alt="System Logo">
        <h1>Counseling Session Report</h1>
        <p><em>Official counseling report generated by OrientaCore System</em></p>
    </div>

    <div class="student-info">
        <h2>Student Information</h2>
        <p><strong>Name:</strong> <?= htmlspecialchars($report['student_name']); ?></p>
        <p><strong>Session Date:</strong> <?= htmlspecialchars($report['session_date']); ?></p>
        <p><strong>Session Topic:</strong> <?= htmlspecialchars($report['session_topic']); ?></p>
        <p><strong>Next Session:</strong> <?= htmlspecialchars($report['next_session']); ?></p>
        <p><strong>Report Created:</strong> <?= htmlspecialchars($report['created_at']); ?></p>
    </div>

    <div class="report-details">
        <h2>Session Details</h2>
        <p><strong>Issues Discussed:</strong><br> <?= nl2br(htmlspecialchars($report['issues_discussed'])); ?></p>
        <p><strong>Counselor Remarks:</strong><br> <?= nl2br(htmlspecialchars($report['counselor_remarks'])); ?></p>
        <p><strong>Recommendations:</strong><br> <?= nl2br(htmlspecialchars($report['recommendations'])); ?></p>
    </div>

    <button class="print-btn" onclick="window.print()">🖨 Print / Save as PDF</button><br>
    <a href="student_reports.php" class="back-link">← Back to Reports</a>

</body>
</html>
